CREATE DATABASE IF NOT EXISTS `VGWEB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `VGWEB`;

CREATE TABLE `GENRE` (
  `id` VARCHAR(42),
  `type` VARCHAR(42),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `APPARTENIR` (
  `id` VARCHAR(42),
  `id_1` VARCHAR(42),
  PRIMARY KEY (`id`, `id_1`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `UTILISATEUR` (
  `id` VARCHAR(42),
  `nom` VARCHAR(42),
  `email` VARCHAR(42),
  `role` VARCHAR(42),
  `isconnected` VARCHAR(42),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `JEU` (
  `id` VARCHAR(42),
  `nom` VARCHAR(42),
  `sortie` VARCHAR(42),
  `synopsis` VARCHAR(42),
  `images` VARCHAR(42),
  `videos` VARCHAR(42),
  `articles` VARCHAR(42),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ACCUEILLIR` (
  `id` VARCHAR(42),
  `id_1` VARCHAR(42),
  `nombre_de_jeux` VARCHAR(42),
  PRIMARY KEY (`id`, `id_1`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PLATEFORME` (
  `id` VARCHAR(42),
  `nom` VARCHAR(42),
  `prix` VARCHAR(42),
  `lancement` VARCHAR(42),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `NOTE` (
  `id` VARCHAR(42),
  `note` VARCHAR(42),
  `critique` VARCHAR(42),
  `id_1` VARCHAR(42),
  `id_2` VARCHAR(42),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `AVOIR` (
  `id` VARCHAR(42),
  `id_1` VARCHAR(42),
  PRIMARY KEY (`id`, `id_1`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `EDITDEV` (
  `id` VARCHAR(42),
  `nom` VARCHAR(42),
  `date` VARCHAR(42),
  `siege` VARCHAR(42),
  `pays_local` VARCHAR(42),
  `description` VARCHAR(42),
  `dev` VARCHAR(42),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `UTILISER` (
  `id` VARCHAR(42),
  `id_1` VARCHAR(42),
  `nombre_de_plateforme` VARCHAR(42),
  PRIMARY KEY (`id`, `id_1`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `APPARTENIR` ADD FOREIGN KEY (`id_1`) REFERENCES `JEU` (`id`);
ALTER TABLE `APPARTENIR` ADD FOREIGN KEY (`id`) REFERENCES `GENRE` (`id`);
ALTER TABLE `ACCUEILLIR` ADD FOREIGN KEY (`id_1`) REFERENCES `PLATEFORME` (`id`);
ALTER TABLE `ACCUEILLIR` ADD FOREIGN KEY (`id`) REFERENCES `JEU` (`id`);
ALTER TABLE `NOTE` ADD FOREIGN KEY (`id_2`) REFERENCES `JEU` (`id`);
ALTER TABLE `NOTE` ADD FOREIGN KEY (`id_1`) REFERENCES `UTILISATEUR` (`id`);
ALTER TABLE `AVOIR` ADD FOREIGN KEY (`id_1`) REFERENCES `JEU` (`id`);
ALTER TABLE `AVOIR` ADD FOREIGN KEY (`id`) REFERENCES `EDITDEV` (`id`);
ALTER TABLE `UTILISER` ADD FOREIGN KEY (`id_1`) REFERENCES `PLATEFORME` (`id`);
ALTER TABLE `UTILISER` ADD FOREIGN KEY (`id`) REFERENCES `EDITDEV` (`id`);